version: "3.9"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=10.40.5.21 # IP del servidor
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - TZ=America/Santiago
      # Para evitar problemas de CORS desde http://10.40.5.21
      - N8N_CORS_ALLOW_ORIGINS=http://10.40.5.21
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_local_files:/files

  frontend:
    image: nginx:alpine
    container_name: practica-frontend
    restart: unless-stopped
    ports:
      - "80:80" # http://10.40.5.21
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

volumes:
  n8n_data:
    external: true
  n8n_local_files:
